version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
      
  # Enable version updates for nuget
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
      
  # Enable version updates for nuget
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20